Repository SAP/cloud-sdk, pull requests merged in 2020-11, with the labels that each got.

#8 Add docu about odata update strategies
  docs/java/features/odata/type-safe-client-odata-v2.mdx
  docs/java/features/odata/type-safe-client-odata-v4.mdx
Labels: documentation

#10 Make Announcement of GA version of Workflow API client lib
  docs/java/features/rest/clients/scp-workflow-rest-api.mdx
Labels: documentation

#11 Add documentation on batch
  docs/js/features/odata/common/batch/batch-intro.mdx
  docs/js/features/odata/common/batch/change-set.mdx
  docs/js/features/odata/common/batch/changeset.mdx
  docs/js/features/odata/common/batch/combine-change-retrieve.mdx
  docs/js/features/odata/common/batch/combining-requests.mdx
  docs/js/features/odata/common/batch/configure-serialization.mdx
  docs/js/features/odata/common/batch/index.jsx
  docs/js/features/odata/common/batch/multiple-change-sets.mdx
  docs/js/features/odata/common/batch/retrieve-request.mdx
  docs/js/features/odata/common/batch/serialization.mdx
  docs/js/features/odata/odata-v2-client.mdx
  docs/js/features/odata/odata-v4-client.mdx
Labels: JavaScript

#14 Extend destinations docu with localhost setup
  docs/java/features/connectivity/destinations.mdx
Labels: Java

#15 Add docu about CAP and SDK integration
  docs/java/guides/cap-sdk-integration.mdx
  sidebars.js
Labels: Java

#16 Remove superfluous section from CAP docu
  docs/java/guides/cap-sdk-integration.mdx
Labels: Java

#26 Update to Destinations
  docs/js/features/connectivity/destination.mdx
Labels: JavaScript

#30 Add sample for the `destinations` env. variable
  docs/js/features/connectivity/destination.mdx
Labels: JavaScript
