Repository SAP/cloud-sdk, pull requests merged in 2022-09, with the labels that each got.

#979 fix: correct any lambda operation example
  docs-js/features/odata/v4/filter-one-to-many.mdx
  docs-js/features/odata/v4/filter-parent-child.mdx
Labels: javascript

#971 chore: adjust proxy settings
  docs-js/guides/bas-external-system.mdx
Labels: javascript

#990 chore: add documentation changeset
  docs-js/features/odata/common/batch/changeset.mdx
  docs-js/features/odata/common/batch/responses.mdx
  docs-js/features/odata/common/batch/retrieve-request.mdx
  docs-js/features/odata/common/function-imports/request-builder.mdx
  docs-js/features/odata/odata-v2-client.mdx
  docs-js/features/odata/odata-v4-client.mdx
  docs-js/features/odata/v2/changeset-example.mdx
  docs-js/features/odata/v2/index.jsx
  docs-js/features/odata/v4/changeset-example.mdx
  docs-js/features/odata/v4/index.jsx
Labels: javascript

#992 fix: fix glob pattern
  .prettierignore
  package.json
  sidebarsDocsCommon.js
  sidebarsDocsJava.js
  sidebarsDocsJs.js
Labels: javascript

#1022 [Java] Release Notes for `3.75.0`
  docs-java/release-notes.mdx
  docs-js/release-notes.mdx
Labels: Java, release notes

#1032 [Java V4] Replace Removed Destination Retrieval Strategy
  docs-java/features/connectivity/destinations.mdx
Labels: Java

#1034 [js] Improve error handling
  docs-js/features/error-handling.mdx
Labels: javascript
