Repository SAP/cloud-sdk, pull requests merged in 2023-02, with the labels that each got.

#1227 [Java] Release Notes for `4.6.0`
  docs-java/release-notes/release-notes-0-to-14.mdx
Labels: Java

#1225 [Java] Add section on Destination Caching improvement with optional user isolation
  docs-java/features/connectivity/destinations.mdx
Labels: Java

#1250 chore: remove `VALUE_IS_UNDEFINED` from OData `servicePath` docs
  docs-js/features/odata/execute-odata-request.mdx
  docs-js/features/odata/generate-odata-client.mdx
  docs-js/tutorials/getting-started/2-execute-odata-request.mdx
Labels: javascript

#1242 Motivate `ExecutorService#invokeAll`
  docs-java/features/multi-tenancy/thread-context.mdx
Labels: Java

#1261 [Java] Fixed typo
  docs-java/faq.mdx
Labels: Java

#1259 chore: Add mail-client to overview
  docs-js/overview.mdx
  static/img/packages_dark.svg
  static/img/packages_light.svg
Labels: javascript

#1267 Fix typo in TS Multi-Tenancy Guide
  docs-js_versioned_docs/version-v2/tutorials/multi-tenant-application.mdx
Labels: javascript

#1273 [JS] Rename inputDir
  docs-js/features/odata/generate-odata-client.mdx
  docs-js/features/openapi/generate-openapi-client.mdx
  docs-js/tutorials/getting-started/2-execute-odata-request.mdx
Labels: javascript

#1265 [JS] Adjust broken dropdown
  docs-js_versioned_docs/version-v1/faq.mdx
  docs-js_versioned_docs/version-v1/features/connectivity/destination-cache-isolation.mdx
  docs-js_versioned_docs/version-v1/features/connectivity/destination.mdx
  docs-js_versioned_docs/version-v1/features/connectivity/generic-http-client.mdx
  docs-js_versioned_docs/version-v1/features/connectivity/on-premise.mdx
  docs-js_versioned_docs/version-v1/features/connectivity/proxy.mdx
  docs-js_versioned_docs/version-v1/features/error-handling.mdx
  docs-js_versioned_docs/version-v1/features/eslint-configuration.mdx
  docs-js_versioned_docs/version-v1/features/logging.mdx
  docs-js_versioned_docs/version-v1/features/odata/execute-odata-request.mdx
  docs-js_versioned_docs/version-v1/features/odata/generate-odata-client.mdx
  docs-js_versioned_docs/version-v1/features/odata/odata-v2-client.mdx
  docs-js_versioned_docs/version-v1/features/odata/odata-v4-client.mdx
  docs-js_versioned_docs/version-v1/features/odata/overview.mdx
  docs-js_versioned_docs/version-v1/features/openapi/execute-openapi-request.mdx
  docs-js_versioned_docs/version-v1/features/openapi/generate-openapi-client.mdx
  docs-js_versioned_docs/version-v1/guides/bas-external-system.mdx
  docs-js_versioned_docs/version-v1/guides/how-to-add-resilience.mdx
  docs-js_versioned_docs/version-v1/guides/how-to-retrieve-jwt.mdx
  docs-js_versioned_docs/version-v1/guides/how-to-use-the-approuter.mdx
  docs-js_versioned_docs/version-v1/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
  docs-js_versioned_docs/version-v1/guides/sdk-in-browser.mdx
  docs-js_versioned_docs/version-v1/guides/trust-and-key-stores.mdx
  docs-js_versioned_docs/version-v1/guides/upgrade-to-version-2.mdx
  docs-js_versioned_docs/version-v1/overview.mdx
  docs-js_versioned_docs/version-v1/release-notes.mdx
  docs-js_versioned_docs/version-v1/video/calm.mdx
  docs-js_versioned_docs/version-v2/guides/bas-external-system.mdx
  docs-js_versioned_docs/version-v2/guides/upgrade-to-version-2.mdx
  docs-js_versioned_sidebars/version-v1-sidebars.json
  src/theme/NavbarItem/DocsVersionDropdownNavbarItem.js
  src/theme/NavbarItem/NavbarNavLink.js
Labels: javascript

#1269 [JS] Add setBasePath to the docs
  docs-js/features/odata/execute-odata-request.mdx
Labels: javascript

#1276 [JS] Remove skipNext
  docs-js/features/middleware.mdx
Labels: javascript

#1283 chore: remove SDK components
  docs-java/faq.mdx
  docs-java/support.mdx
  docs-java_versioned_docs/version-v3/faq.mdx
  docs-js/support.mdx
  docs-js_versioned_docs/version-v1/faq.mdx
  docs-js_versioned_docs/version-v2/support.mdx
  docs/support.mdx
Labels: don't merge
